import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import { join } from "node:path";
import {
	findBinManifest,
	parseMd5Manifest,
	verifyRepackBins,
} from "./bin-verify";

let setupDir: string;

const md5 = (content: string): string =>
	crypto.createHash("md5").update(content).digest("hex");

beforeEach(() => {
	setupDir = fs.mkdtempSync(join(os.tmpdir(), "fatboy-bin-verify-"));
	fs.mkdirSync(join(setupDir, "MD5"));
});

afterEach(() => {
	fs.rmSync(setupDir, { recursive: true, force: true });
});

describe("bin verification", () => {
	test("parses md5sum lines and ignores comments and QuickSFV noise", () => {
		const entries = parseMd5Manifest(
			[
				"; Generated by WIN-SFV32 v1.1",
				"",
				`${"a".repeat(32)} *fg-01.bin`,
				`${"B".repeat(32)}  sub\\fg-02.bin`,
				"not a manifest line",
			].join("\r\n"),
		);
		expect(entries).toEqual([
			{ hash: "a".repeat(32), name: "fg-01.bin" },
			{ hash: "b".repeat(32), name: "sub/fg-02.bin" },
		]);
	});

	test("finds the conventional manifest and verifies bins beside setup.exe", async () => {
		fs.writeFileSync(join(setupDir, "fg-01.bin"), "payload one");
		fs.writeFileSync(join(setupDir, "fg-02.bin"), "payload two");
		fs.writeFileSync(
			join(setupDir, "MD5", "fitgirl-bins.md5"),
			[
				`${md5("payload one")} *fg-01.bin`,
				`${md5("payload two")} *fg-02.bin`,
				`${md5("gone")} *fg-optional-gone.bin`,
			].join("\n"),
		);

		const manifestPath = findBinManifest(setupDir);
		expect(manifestPath).toBe(join(setupDir, "MD5", "fitgirl-bins.md5"));

		const progress: number[] = [];
		const result = await verifyRepackBins(manifestPath!, (value) =>
			progress.push(value),
		);
		expect(result.verified).toBe(2);
		expect(result.corrupt).toEqual([]);
		expect(result.missing).toEqual(["fg-optional-gone.bin"]);
		expect(progress.at(-1)).toBe(100);
	});

	test("reports corrupt files by manifest name", async () => {
		fs.writeFileSync(join(setupDir, "fg-01.bin"), "tampered");
		fs.writeFileSync(
			join(setupDir, "MD5", "fitgirl-bins.md5"),
			`${md5("pristine")} *fg-01.bin`,
		);

		const result = await verifyRepackBins(findBinManifest(setupDir)!);
		expect(result.corrupt).toEqual(["fg-01.bin"]);
		expect(result.verified).toBe(0);
	});
});
